config/routes.rb
Rails.application.routes.draw do
  get 'account_activations/edit'

  root                'static_pages#home'
  get 'contact'   =>  'static_pages#contact'
  get 'about'     =>  'static_pages#about'
  get 'help'      =>  'static_pages#help'
  get 'signup'    =>  'users#new'
  get 'login'     =>  'sessions#new'
  post 'login'    =>  'sessions#create'
  delete 'logout' =>  'sessions#destroy'

  get 'sessions/new'
  resources :users

  # rails generate controller AccountActivations \
  # edit --no-test-framework
  resources :account_activations, only: [:edit]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token
  before_save   :downcase_email
  before_create :create_activation_digest

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: {minimum: 6}

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent session.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  private

  # Converts email to all lower-case
  def downcase_email
    self.email = email.downcase
  end

  #creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_digest)
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      # log the user in and redirect to the user's show page
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      # Create an error message
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Sử dụng bộ lọc để kiểm tra trạng thái đăng nhập
  # Nếu người dùng truy cập vô edit, update thì chạy vào 'logged_in_user' để kiểm tra
  before_action :logged_in_user,  only:  [:index, :edit, :update, :destroy]
  before_action :correct_user,    only:  [:edit, :update]
  before_action :admin_user,      only:  :destroy

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  # Xác nhận người dùng đã đăng nhập
  # Confirms a logged-in user
  def logged_in_user
    unless logged_in?       # nếu chưa đăng nhập thì chạy block dưới
      store_location
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end

  # Xác nhận user đúng
  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to (root_url) unless current_user.admin?
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # returns the current logged-in user (if any)
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  # return true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/account_activations/edit.html.erb
<h1>AccountActivations#edit</h1>
<p>Find me in app/views/account_activations/edit.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright &copy 2015 <a target="_blank" href="http://facebook.com/haha.zi">Jindo Kuyo</a>
  </small>

  <nav>
    <ul>
      <li><%= link_to "Giới thiệu", about_path %></li>
      <li><%= link_to "Liên hệ", contact_path %></li>
      <li><a href="#">Tin tức</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="nav navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Jindo Blog", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Trang chủ", root_path %></li>
        <li><%= link_to "Trợ giúp", help_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Danh sách Users", users_path  %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Tài khoản <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Trang cá nhân", current_user %></li>
                <li><%= link_to "Sửa thông tin", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Thoát", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Đăng nhập", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield(:title) %> | Jindo Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= @user.errors.count %> errors.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="center jumbotron">
  <h1>Sample App - About</h1>

  <h2>
    This is the home page for the
    <%= link_to "Blog", root_path %>
    sample application.
  </h2>

</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<div class="center jumbotron">
  <h1>Sample App - Help</h1>

  <h2>
    This is the home page for the
    <%= link_to "Blog", root_path %>
    sample application.
  </h2>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
  <h1>Blog App - Home</h1>

  <h2>
    This is the home page for the
    <%= link_to "Blog", root_path %>
    sample application.
  </h2>

  <div class="button-signup">
    <% if logged_in? %>
    <p>Xin chào, hãy bắt đầu trải nghiệm những tính năng của blog :)</p>
    <% else %>
        <%= link_to "Đăng ký ngay!", signup_path, class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
</div>

<!-- <%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org' %> -->

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, data: { confirm: "Bạn có thực sự muốn xoá người này?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="center jumbotron">
  <h1>Update your profile</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>

          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>


          <%= f.submit "Save change", class: "btn btn-primary" %>

      <% end %>

      <div class="gravatar_edit">
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails">Change</a>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
  <h1>All users</h1>


  <%= will_paginate %>
  <ul class="users">
    <%= render @users %>
  </ul>
  <%= will_paginate %>

</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>

<div class="center jumbotron">
  <h1>Sign In</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>

          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>


          <%= f.submit "Create my account", class: "btn btn-primary" %>

      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="center jumbotron">

  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>

</div>

app/views/users/sua.html.erb
<% provide(:title, "Edit user") %>

<div class="center jumbotron">
  <h1>Update your profile</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>

          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>


          <%= f.submit "Save change", class: "btn btn-primary" %>

      <% end %>

      <div class="gravatar_edit">
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails">Change</a>
      </div>
    </div>
  </div>
</div>